baseURL = "/intranet"
languageCode = "en-gb"
title = "UKWA Reports"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
copyright = ""

[params]
    author = "UK Web Archive"
    description = "Technical reports"
    githubUsername = "#"
    accent = "#2e6dd9"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    css = ["https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/crawls/"
    name = "Crawls"
    weight = 2

[[menu.main]]
    url = "/reports/"
    name = "Reports"
    weight = 3

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 4

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:web-archivist@bl.uk"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ukwa/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/UKWebArchive/"
    name = "twitter"
    weight = 3

